### ISSUE TITLE
Plates version 2

### ISSUE THREAD

**Issue by petsagouris** [rchouinard/silex-plates-provider#1]
I am getting the following while trying to install with Plates 2

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for rych/silex-plates-provider v1.0.0 -> satisfiable by rych/silex-plates-provider[v1.0.0].
    - rych/silex-plates-provider v1.0.0 requires league/plates 1.0.* -> no matching package found.
```

**Comment by rchouinard** [comment]
I haven't tested and prepared a release against Plates 2 yet, so the
package is constrained to Plates 1 for now. I'll see if I can get a new
release for Plates 2 ready. The changes should be trivial.

**Comment by petsagouris** [comment]
Cheers for the quick response. I will be grateful for this when you make it.

**Comment by rchouinard** [comment]
I've started a new branch `plates2`. I can't see any reason simply updating the Composer constraint to include Plates 2 won't work, I don't see any BC breaks in the API as far as the provider is concerned. If you don't mind using a dev branch (and helping me test things), you can point your composer.json to `"rych/silex-plates-provider": "dev-plates2@dev"` and it should let you use the provider with Plates 2. Feedback on this branch would be very welcome before I cut a full release from it.

The amount of work required to get this working will determine the next release version. I'm hopeful this can be a simple point release and I can maintain compatibility with both Plates 1 and Plates 2.

**Comment by rchouinard** [comment]
Tagged v1.0.1 with support for Plates 2.
